### ISSUE TITLE
Select Image Error Report

### ISSUE THREAD

**Issue by nak-attak** [esmBot/esmBot#396] opened 2023-07-03 16:41 UTC
### Command that caused the error

Pressed the "..." on an image, pressed "Apps", pressed "Select Image".

### Image that caused the error

https://tenor.com/view/rrane-battal-rrane-battal-k%C4%B1zg%C4%B1n-battal-k%C4%B1zg%C4%B1n-gif-25355985

### Steps to reproduce

1. Post the attached gif in chat
2. Go to '...'
3. Click on 'Apps'
4. Click on 'Select Image'
5. See error

### Self-hosted instance?

No

### Error file

```
[error (1).txt](https://github.com/esmBot/esmBot/files/11938924/error.1.txt)
```

### Additional context

I tried selecting the gif 1 hour & 18 minutes after the gif was posted.

**Comment by TheEssem** [comment] 2023-07-04 21:02
Duplicate of #338

**Closed by TheEssem** 2023-07-04 21:02 UTC
Labels: bug
