### ISSUE TITLE
Bot stops responding, but reports no errors

### ISSUE THREAD

**Issue by dominic-03** [esmBot/esmBot#383] opened 2023-05-13 20:01 UTC
After the bot runs for a while, it eventually suddenly stops responding. When this occurs, there is no log messages (normal or debug) giving a hint to the problem. The bot remains "online" but shows "The application did not respond" or "This interaction failed" on slash commands or (in the case of self-hosts) provides no output whatsoever on legacy commands.

There have been multiple reports of this happening on the main bot, and I have also experienced it on my self-host. This problem did not happen (at least, on my self-host) prior to the migration from Eris to Oceanic.

**Comment by TheEssem** [comment] 2023-06-12 00:09
I'm thinking this might be an Oceanic issue, last time I was able to reproduce this it did try to run the command but anything involving Discord API calls just stalled. I've updated the bot to Oceanic 1.7 if y'all want to see if that fixes it, however if it doesn't I'll bring it up with the maintainers.

**Comment by TheEssem** [comment] 2023-06-15 21:18
Hmmm, in that case I'll try and look further into Oceanic's source to figure out what could be up.

**Comment by TheEssem** [comment] 2023-06-16 00:36
Actually @dominic-03, could we chat about this in Discord DMs? Remove the `await this.acknowledge();` line from commands/general/eval.js, restart the bot, and DM me when it happens again.

**Comment by KittySam2** [comment] 2023-06-17 19:24
How do I fix this though? Do I have to do something to fix the error?

**Comment by dominic-03** [comment] 2023-06-17 20:16
> How do I fix this though? Do I have to do something to fix the error?

There is no fix yet, the problem is still being worked out

**Comment by TheEssem** [comment] 2023-06-18 15:13
I believe I may have found part of the cause for this, the SequentialBucket for the interaction response endpoint can sometimes get stuck on `true` causing it to completely stop responding:
![image](https://github.com/esmBot/esmBot/assets/21112968/b6542077-fabe-4d65-a051-e9fba01e27b3)
Setting it back to `false` using the eval command makes the bot start responding to commands instantly. Interestingly, the Oceanic SequentialBucket class was copied mostly from Eris, which makes this slightly more difficult to debug since this issue didn't happen in Eris.

**Comment by TheEssem** [comment] 2023-06-21 01:58
Found the fix! Submitted a PR to Oceanic (OceanicJS/Oceanic#72), so once that gets merged consider this fixed.

**Comment by dominic-03** [comment] 2023-06-21 04:02
Woohoo!

**Comment by TheEssem** [comment] 2023-06-21 17:40
Pull request merged, I also applied the patch on the main bot and it seems to be doing well. Just switched Oceanic to the dev branch, so this should be fixed for sure now.

**Closed by TheEssem** 2023-06-21 17:40 UTC
Labels: bug

**Comment by Lassoloc** [comment] 2025-08-03 08:38
I'm receiving this issue again, if it was fixed that fix appears to have been broken. Attempting to use the main instance (not self-hosted) and being told the application isn't responding. Not sure where else to bring this up besides here

![Screenshot_20250803-043436.png](https://github.com/user-attachments/assets/05e22403-b00d-4286-9338-f91e0cdb17ea)
