### ISSUE TITLE
DiscordRESTError when running /cat

### ISSUE THREAD

**Issue by supercat3point0** [esmBot/esmBot#400] opened 2023-07-07 20:50 UTC
### Command that caused the error

/cat

### Steps to reproduce

1. Use `/cat` command

### Self-hosted instance?

No

### Error file

```
Message: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:176:46)
```

**Comment by TheEssem** [comment] 2023-07-08 04:14
Duplicate of #338

**Closed by TheEssem** 2023-07-08 04:14 UTC
Labels: bug
