### ISSUE TITLE
bot is down

### ISSUE THREAD

**Issue by KittySam2** [esmBot/esmBot#392] opened 2023-06-15 18:41 UTC
### Describe the bug

wont let me caption or deepfry images

### Steps to reproduce

1. type any command
2. send command once you’re done typing it
3. congrats it gave you the same error message I’m getting

### Expected behavior

pretty sure most people know how it’s supposed to work?

### Screenshots

![IMG_3112](https://github.com/esmBot/esmBot/assets/136747569/a3eb5f95-9d56-429d-9d44-9a24c5ca1467)

### Self-hosted instance?

No

**Comment by TheEssem** [comment] 2023-06-15 21:17
Duplicate of #383

**Closed by TheEssem** 2023-06-15 21:17 UTC
Labels: bug
