### ISSUE TITLE
&caption <text> makes the bot crash when ran without attachement and with no messages since a long time

### ISSUE THREAD

**Issue by CallMePixelMan** [esmBot/esmBot#213] opened 2022-01-08 10:57 UTC
### Command that caused the error

&caption test

### Steps to reproduce

- Don't talk in a discord channel for a while / invite the bot on a server with a dead chat
- Run the `&caption <message>` command in the channel with very old messages without adding an attachement
- Done

### Self-hosted instance?

No

### Error file

```
Message: TypeError: Cannot read properties of undefined (reading '0')
    at getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:62:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async checkImages (file:///home/esmBot/esmBot/utils/imagedetect.js:106:16)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:144:20)
    at async CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:56:23)
    at async default (file:///home/esmBot/esmBot/events/messageCreate.js:105:20)

Stack Trace: TypeError: Cannot read properties of undefined (reading '0')
    at getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:62:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async checkImages (file:///home/esmBot/esmBot/utils/imagedetect.js:106:16)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:144:20)
    at async CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:56:23)
    at async default (file:///home/esmBot/esmBot/events/messageCreate.js:105:20)
```

### Additional context

I invited the bot on a guild I barely use (only to test some bots, and where no-one talk), ran the command `&caption` for the first time without a file, and the bot crashed. 
I assume that the bot tried to lookup for images in the messages where he can't access because of the API having a 14 days limit, and crashed because he couldn't find an attachement in the message of my command, and couldn't find any image in the messages above too.

After using the bot to make the caption in the same channel, I was abble to reproduce the bug by deleting all messages to the same last message.

![image](https://user-images.githubusercontent.com/65821351/148641488-c268aec7-21a3-4758-ad2e-66f581e6bd2e.png)

**Comment by TheEssem** [comment] 2022-01-08 19:31
Took a look at this, interestingly the error points to the part of the code where Tenor GIFs are handled. Was the last GIF posted from Tenor by chance, disregarding the date/time?

**Comment by CallMePixelMan** [comment] 2022-01-08 21:04
Yup

**Comment by TheEssem** [comment] 2022-01-08 22:02
Figured as much, can you send over the link to the GIF in question? Gonna try and look into this some more

**Comment by CallMePixelMan** [comment] 2022-01-09 17:57
Here's it [link](https://tenor.com/view/troll-troll-face-ragememe-rageface-trolling-gif-4929853) (this is the real link)

**Comment by CallMePixelMan** [comment] 2022-01-13 14:24
Hey, got any news ? Should I close the issue ?

**Comment by TheEssem** [comment] 2022-01-13 20:57
> Hey, got any news ? Should I close the issue ? 

I feel like it could be due to a change in Discord's embed format for tenor gifs, not too sure however. Probably gonna leave it open since it is still a bit of an issue

**Comment by XenoPanther** [comment] 2022-01-14 23:26
It likely is an issue with the embed format as I am getting several commands failing with the error 

Message: Request ended prematurely due to a closed connection

Stack Trace: undefined

**Comment by TheEssem** [comment] 2022-01-15 00:59
> It likely is an issue with the embed format as I am getting several commands failing with the error
> 
> Message: Request ended prematurely due to a closed connection
> 
> Stack Trace: undefined

This issue is unrelated, I've attempted to handle that with 72efad0

**Comment by TheEssem** [comment] 2022-10-12 04:39
This *should* be fixed by now, especially on the main bot where message content is no longer available. If this is still an issue on self-hosted instances, please comment and I'll reopen; I haven't been able to reproduce this at all.

**Closed by TheEssem** 2022-10-12 04:39 UTC
Labels: bug
