### ISSUE TITLE
Tenor GIF speed esmBot glitch

### ISSUE THREAD

**Issue by lihns0** [esmBot/esmBot#122] opened 2021-05-17 18:16 UTC
**Command that caused the error**
&speed

**Image that caused the error**
https://media.tenor.co/videos/ab0fa2d333ff5d30728c1a7bb84442a4/mp4

**To Reproduce**
1. Go to Tenor GIF selector
2. Search Billy Cobham
3. Click GIF of the man drumming
4. Use the &speed command
5. See error

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?
No.
**Error file**
```
Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:363:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/esmBot/esmBot/utils/image.js:154:21
    at new Promise (<anonymous>)
    at /home/esmBot/esmBot/utils/image.js:153:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Additional context**

**Comment by TheEssem** [comment] 2021-05-17 20:05
Duplicate of #70

**Closed by TheEssem** 2021-05-17 20:05 UTC
