### ISSUE TITLE
wont make gifs anymore

### ISSUE THREAD

**Issue by MrPieMaaan** [esmBot/esmBot#394] opened 2023-06-24 07:31 UTC
### Command that caused the error

/gif image:

### Image that caused the error

it doesnt work with any image

### Self-hosted instance?

Yes

### Error file

Message: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:182:24)
    at /home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:129:46
    at Immediate._onImmediate (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:170:9)
    at processImmediate (node:internal/timers:466:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'

### Additional context

wont let me make any funny gifs anymore

**Comment by TheEssem** [comment] 2023-06-24 14:04
Duplicate of #393

**Closed by TheEssem** 2023-06-24 14:04 UTC
Labels: bug
