### ISSUE TITLE
esmBot not working

### ISSUE THREAD

**Issue by WolfburningXx** [esmBot/esmBot#368] opened 2023-04-04 16:55 UTC
### Command that caused the error

caption and selection image

### Self-hosted instance?

Yes

### Error file

[error.txt](https://github.com/esmBot/esmBot/files/11150997/error.txt)

**Comment by TheEssem** [comment] 2023-04-06 14:28
Duplicate of #338/#339

**Closed by TheEssem** 2023-04-06 14:28 UTC
Labels: bug
