### ISSUE TITLE
Error when using commands.

### ISSUE THREAD

**Issue by zekstering** [esmBot/esmBot#410] opened 2023-09-20 15:38 UTC
### Command that caused the error

/gif, /caption, /reverse, /8ball, etc.

### Steps to reproduce

1. Go to a channel
2. Use any command
3. See error

### Self-hosted instance?

No

### Error file

```
Message: DiscordRESTError: Unknown interaction on POST /api/v10/interactions/1154075950821146676/aW50ZXJhY3Rpb246MTE1NDA3NTk1MDgyMTE0NjY3Njo4TGoyNkRWMFg1RFZralk3cEdWUThJNXBnZ1hLMWxVb1dsaEx0Q0NHRk9Ib2xpdkFSV2hxanprbVlwcVl6N3pEaHh3dk1tRzFxYUVadW1rbTRHcEM1ckdXZFpWVkN0b2VRckFsTjRqWElwVGd5cWFWb0VndGlMS0VBRFlOeHBoQg/callback
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:179:46)
```

### Additional context

Just started happening today, I used the select image feature and got the message and the error log, so i sent it here. Even though it says that "I ran into an error while running this command." it still seems to do it successfully (such as giving an 8ball answer, making a caption for a gif, sending an image of a dog, etc.) and it says that "I ran into an error.." with the error.txt file. Just thought I'd post this here as it said. Also i added this bot quite some time ago, the server is only with me and esmBot, to use it for memes and such, maybe I just need to remove it and add it again. Hope to have helped with something!

**Comment by TheEssem** [comment] 2023-09-20 17:42
Duplicate of #338

**Closed by TheEssem** 2023-09-20 17:42 UTC
Labels: bug
