### ISSUE TITLE
Speed broken

### ISSUE THREAD

**Issue by Yarnamite** [esmBot/esmBot#121] opened 2021-05-17 14:41 UTC
Doing the slow command on a gif that is predominantly black and white (it may just be easier to notice on black and white images, i dont know) produces a slowed down version of the gif but it is often distorted with blank frames etc

1. post a black and white gif
2. do the slow command
3. wait for the gif to be edited
4. see painful results

I would expect the gif to simply be the same gif with a higher frame rate.

video of results:
https://user-images.githubusercontent.com/66518629/118507283-ffe80200-b725-11eb-8724-ac178793f2f1.mp4

gif used:
https://user-images.githubusercontent.com/66518629/118507551-3f165300-b726-11eb-8ea5-1a7732d6ecea.gif

**Comment by samhza** [comment] 2021-05-17 15:05
This incorrect behavior was introduced in e6b4db6e3ee8c889d456c025e735717e3b0e005f, which uses a search for 3 bytes to try and find the delays in the GIF to modify them. This approach does not work on all GIFs like actually properly reading the GIF would, because there is no guarantee that all instances of the bytes 21 F9 04 are actually preceding the bytes with the delay.

**Comment by TheEssem** [comment] 2021-05-17 15:08
> This incorrect behavior was introduced in [e6b4db6](https://github.com/esmBot/esmBot/commit/e6b4db6e3ee8c889d456c025e735717e3b0e005f), which uses a search for 3 bytes to try and find the delays in the GIF to modify them. This approach does not work on all GIFs like actually properly reading the GIF would, because there is no guarantee that all instances of the bytes 21 F9 04 are actually preceding the bytes with the delay.

Actually, this is incorrect. The changed logic has not made it into the main bot yet, and thus the behavior is with the old logic. Just tested it on esmBot Dev (which has the new changes) and it worked as intended. This could possibly be a result of the ImageMagick transparency optimizations.

**Comment by samhza** [comment] 2021-05-17 15:20
Ah. The new GIF approach could in theory mess up the colors or pixels of a correct GIF but I haven't really seen that happen on a real GIF yet so yeah isn't really an issue yet.

**Comment by Yarnamite** [comment] 2021-05-17 17:40
cool, i have literally no idea what anyone just said

**Comment by TheEssem** [comment] 2021-05-18 00:03
Looks to be fixed now, closing.

**Closed by TheEssem** 2021-05-18 00:03 UTC
