### ISSUE TITLE
Unknown interaction (response)

### ISSUE THREAD

**Issue by newfuckingplayer** [esmBot/esmBot#339] opened 2022-12-18 18:54 UTC
Message: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.createMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:151:46)
    at default (file:///root/esmBot/events/interactionCreate.js:30:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 10062,
  method: 'POST',
  resBody: { message: 'Unknown interaction', code: 10062 },
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: [Object],
    [Symbol(headers)]: [HeadersList]
  }
}

Stack Trace: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.createMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:151:46)
    at default (file:///root/esmBot/events/interactionCreate.js:30:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by TheEssem** [comment] 2022-12-18 23:21
Duplicate of #338

**Comment by TheEssem** [comment] 2022-12-18 23:22
Seems related to #338, although it wasn't caused the same way.

**Comment by TheEssem** [comment] 2024-08-07 00:14
This bug is caused by the same issue as #338, closing.

**Closed by TheEssem** 2024-08-07 00:14 UTC

**Comment by newfuckingplayer** [comment] 2024-08-08 18:03
this shit was 2 years ago
what the fuck
