### ISSUE TITLE
"Module did not self-register" when running selfhosted version of bot

### ISSUE THREAD

**Issue by IoIxD** [esmBot/esmBot#172] opened 2021-11-10 02:22 UTC
### Command that caused the error

&caption, after being done a second time.

### Image that caused the error

N/A, it happened on both images and gifs.

### Steps to reproduce

1. Start up the bot
2. Run &caption on an image
3. Get the result
4. Run &caption again
5. Get the error any subsequent times.

### Self-hosted instance?

Yes

### Error file

```
Message: Module did not self-register: '/root/esmBot/build/Release/image.node'.

Stack Trace: undefined
```

### Additional context

I have tried removing `node_modules` and doing `npm install` again multiple times. `npm update` doesn't work either. I have also tried running as root, but `npm install` gives a permission denied error while trying to create `build/`, and `npm start` gives a "module not found" error.

**Comment by IoIxD** [comment] 2021-11-10 02:24
Running `&meme` yields a different error:
```
Message: Cannot find module '../build/Release/image.node'
Require stack:
- /root/esmBot/utils/image-runner.js

Stack Trace: undefined
```

**Comment by TheEssem** [comment] 2021-11-22 05:31
> Running `&meme` yields a different error:
> 
> ```
> Message: Cannot find module '../build/Release/image.node'
> Require stack:
> - /root/esmBot/utils/image-runner.js
> 
> Stack Trace: undefined
> ```

This error in particular is a possible sign that you need to rebuild the image natives using `npm run build`, not sure about the other one however.

**Comment by Myl0g** [comment] 2021-11-24 20:22
Reproduced on a Debian 11 instance with Node 16 and Node 17 + NPM 18. Occurs both on master and v1.6.4. Tried everything @IoIxD did to no avail. I also did `sudo npm install`, and while it appeared to work perfectly, doing `npm start` either with or without sudo gave this error:

```
[2021-11-24 20:21:52]: [MAIN] - error | DiscordHTTPError: 401 Unauthorized on GET /api/v9/gateway/bot
    at RequestHandler.request (/home/esmbot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:75:15)
    at Client.getBotGateway (/home/esmbot/esmBot/node_modules/eris/lib/Client.js:2135:36)
    at Admiral.calculateShards (file:///home/esmbot/esmBot/node_modules/eris-fleet/dist/sharding/Admiral.js:1796:41)
    at file:///home/esmbot/esmBot/node_modules/eris-fleet/dist/sharding/Admiral.js:1185:22
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
```

**Comment by ctaetcsh** [comment] 2021-12-22 10:29
Also encountering this issue with anything that needs the image.node module. Was able to get &caption to work once before all the other failed. 
![image](https://user-images.githubusercontent.com/48845980/147078405-6e2c596d-b9f8-445f-8f7d-2aa25fad29a3.png)

**Comment by 18swenskiq** [comment] 2022-01-09 01:32
Bumping this in that I am having the exact same issue, just pulled the repo today. The first image you attempt to process works correctly, then the second and subsequent images throw the error

**Comment by Haaselh0ff** [comment] 2022-01-10 15:46
Noticing the exact same thing is happening to me. The first image will work just fine but then everything else just throws me that error

**Comment by TheEssem** [comment] 2022-01-26 21:59
Can anyone who's experiencing this issue try building again with 715ed3b or the latest commit applied? I've made some changes to the building process which could have a possibility of handling this issue.

**Comment by 18swenskiq** [comment] 2022-01-27 22:14
> Can anyone who's experiencing this issue try building again with [715ed3b](https://github.com/esmBot/esmBot/commit/715ed3bb7b2c3071358e027b45d9a6547740a7f1) or the latest commit applied? I've made some changes to the building process which could have a possibility of handling this issue.

Tested on current commit. Basically the same issue, here
![image](https://user-images.githubusercontent.com/10033936/151452342-5634a301-03b4-4d3c-aad9-81c8e1654d44.png)

The same thing appears in the log file:
```
[2022-01-27 22:09:02]: [ERROR] - Cluster 0 | Error occurred with command message $meme test,test: Cannot find module '../build/Release/image.node'
Requires stack:
- /root/esmBot/utils/image-runner.js
```

**Comment by TheEssem** [comment] 2022-01-29 21:10
Looked into this a bit more, it seems like this happens because the bot isn't requiring the native module on the main thread, which is necessary so that it can share the memory with the worker threads (iirc).

I've gone ahead and pushed 6aa1bf7 and 5da6207 to try and fix the issue, try it now with those commits applied.

**Comment by 18swenskiq** [comment] 2022-01-29 21:59
I wish I could say that it worked now, but unfortunately no. Upon first trying to launch it, I get an issue just that "createRequire is not defined". 
![image](https://user-images.githubusercontent.com/10033936/151678823-6a394dbd-e877-40df-9fd3-443e4939057a.png)

I went into image.js and manually added the `import { createRequire } from 'module';` line myself just to get passed this error, and I get basically the same issue as before

![image](https://user-images.githubusercontent.com/10033936/151678868-e067bd4b-61c0-407e-b3f6-67eb394acc52.png)

**Comment by TheEssem** [comment] 2022-01-29 22:15
Ah, my mistake; the paths were messed up. Just pushed a fix, try now.

**Comment by Myl0g** [comment] 2022-01-29 22:52
With that fix, I'm getting this issue:

```
[2022-01-29 22:51:23]: [INFO] - Finished loading events. 
[2022-01-29 22:51:23]: [INFO] - Started worker 3. 
[2022-01-29 22:51:27]: [ERROR] - Service image | Error: connect ECONNREFUSED 127.0.0.1:3762 
[2022-01-29 22:51:27]: [WARN] - Service image | Lost connection to localhost:3762, attempting to reconnect in 5 seconds... 
[2022-01-29 22:51:32]: [ERROR] - Service image | Error: connect ECONNREFUSED 127.0.0.1:3762 
```

**Comment by TheEssem** [comment] 2022-01-29 23:02
> With that fix, I'm getting this issue:
> 
> ```
> [2022-01-29 22:51:23]: [INFO] - Finished loading events. 
> [2022-01-29 22:51:23]: [INFO] - Started worker 3. 
> [2022-01-29 22:51:27]: [ERROR] - Service image | Error: connect ECONNREFUSED 127.0.0.1:3762 
> [2022-01-29 22:51:27]: [WARN] - Service image | Lost connection to localhost:3762, attempting to reconnect in 5 seconds... 
> [2022-01-29 22:51:32]: [ERROR] - Service image | Error: connect ECONNREFUSED 127.0.0.1:3762 
> ```

Set `API` in the .env file to false.

**Comment by Myl0g** [comment] 2022-01-30 00:10
Whoops! I started a new box and accidentally enabled that option.

The fix works! Everything is up to par on my end. Thanks for the fix!

**Comment by TheEssem** [comment] 2022-01-30 03:03
No prob, good to know it works! :)

Closing now, if anyone else is still having this issue with the new commit then I'll reopen it.

**Closed by TheEssem** 2022-01-30 03:03 UTC
Labels: bug

**Comment by 18swenskiq** [comment] 2022-01-30 04:08
I am still getting the same issue as before, I specifically grabbed the commit where you fixed the include statement. I even completely reinstalled all dependencies/libs/ImageMagick and everything else just in case

![image](https://user-images.githubusercontent.com/10033936/151686227-6924f1e1-e530-4608-b1f0-2eaf7623bd4d.png)

**Comment by TheEssem** [comment] 2022-01-30 04:28
> I am still getting the same issue as before, I specifically grabbed the commit where you fixed the include statement. I even completely reinstalled all dependencies/libs/ImageMagick and everything else just in case
> 
> ![image](https://user-images.githubusercontent.com/10033936/151686227-6924f1e1-e530-4608-b1f0-2eaf7623bd4d.png)

Did you make sure to run `npm run build`?

**Comment by oatmealine** [comment] 2022-01-30 13:36
issue seems fixed on my end, ty

**Comment by 18swenskiq** [comment] 2022-01-30 15:33
> > I am still getting the same issue as before, I specifically grabbed the commit where you fixed the include statement. I even completely reinstalled all dependencies/libs/ImageMagick and everything else just in case
> > ![image](https://user-images.githubusercontent.com/10033936/151686227-6924f1e1-e530-4608-b1f0-2eaf7623bd4d.png)
> 
> Did you make sure to run `npm run build`?

Fixed now, though the [guide](https://github.com/esmBot/esmBot/wiki/Setup) doesn't say to run this command. Thanks!
