### ISSUE TITLE
Music Error

### ISSUE THREAD

**Issue by Jwilh153** [esmBot/esmBot#481] opened 2024-11-26 19:56 UTC
### Command that caused the error

/music play

### Steps to reproduce

Simply try playing any music at all. Bot joins for half a second, then leaves.

### Self-hosted instance?

No

### Error file

Message: RestError: Session not found
    at Rest.fetch (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.1.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:949:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.sendServerUpdate (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.1.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:709:5)
    at async Shoukaku.joinVoiceChannel (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.1.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:1332:7)
    at async play (file:///home/esmBot/esmBot/utils/soundplayer.js:133:32)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=101:20:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:57:20) {
  timestamp: 1732650748400,
  status: 404,
  error: 'Not Found',
  trace: undefined,
  path: '/v4/sessions/9bec3iu6i0g0i1nx/players/1122009561289719869'
}

Stack Trace: RestError: Session not found
    at Rest.fetch (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.1.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:949:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.sendServerUpdate (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.1.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:709:5)
    at async Shoukaku.joinVoiceChannel (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.1.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:1332:7)
    at async play (file:///home/esmBot/esmBot/utils/soundplayer.js:133:32)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=101:20:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:57:20)

**Comment by TheEssem** [comment] 2024-11-26 22:25
Duplicate of #459

**Closed by TheEssem** 2024-11-26 22:25 UTC
Labels: bug
