### ISSUE TITLE
ESMBot crashes if using vertical mirroring commands on gifs over a certain combined size and framecount

### ISSUE THREAD

**Issue by NullSnapshot** [esmBot/esmBot#424] opened 2024-01-05 07:19 UTC
### Describe the bug

A user on one of the servers I self-host ESMbot used the hooh command on a gif and it caused my self-host to crash. I did some experimentation and was able to create a test gif that reliably crashes ESMbot instances, 

Presumably this due to the way that the libvips API handles the arrayjoin command in https://github.com/esmBot/esmBot/blob/752d0956d655a22a357ddd75a8861fa6f2dd5b7b/natives/mirror.cc#L38. The same test gif below works fine in the case of horizontal mirroring, and the commands work normally for gifs with a smaller size. The only other thing I can think of is that somehow the actual frame being written to buffer gets out of sequence with the DataSize value when it's written into buffer at https://github.com/esmBot/esmBot/blob/752d0956d655a22a357ddd75a8861fa6f2dd5b7b/natives/mirror.cc#L68. However, I don't believe that's the case because the behavior happens regardless of whether the expanded image in libvips has an even or odd height.

### Steps to reproduce

1. Save the gif below
2. run /hooh using the gif as an image
3. Observe the bot crash (or generate a "can't contact image server" message in the case of the Dev instance)

### Expected behavior

For it not to crash (like how it doesn't for HaaH or WaaW).

### Screenshots

Test gif that generates crash
![testgifpleaseignore](https://github.com/esmBot/esmBot/assets/5078676/5a3dcc96-c1af-4f4f-95cf-b517f4f21f40)
(The flash is necessary. If it's just all white for all frames, it works fine.)

### Self-hosted instance?

Yes

### Additional context

This also occurs with the esmBot hosted instances.

**Comment by NullSnapshot** [comment] 2024-01-05 07:20
Forgot to mention, when it crashes, it segfaults. I don't know if self-hosts dump their stack anywhere. I couldn't find it myself.

**Comment by Vultumast** [comment] 2024-01-07 12:45
Problem def seems to stem from 
https://github.com/esmBot/esmBot/blob/752d0956d655a22a357ddd75a8861fa6f2dd5b7b/natives/mirror.cc#L68
``out`` *seems* to be a correct and valid pointer address but this line isn't raising ``vips::VError`` so it might be something on the library's end.

**Comment by TheEssem** [comment] 2024-01-07 20:34
Yeah, this seems like an issue with libvips; would need to try and reproduce it outside of the bot to make sure, though.

**Comment by TheEssem** [comment] 2024-01-07 20:43
Actually, I wonder; does this happen on libvips 8.14? It seems like it could be related to some changes in 8.15, judging from a quick look at the issue tracker (libvips/libvips#3786 and libvips/libvips#3803 might be related).

**Comment by TheEssem** [comment] 2024-01-29 03:38
Recreated the problematic code using pyvips to verify that it isn't just an issue with esmBot's handling:
```py
#!/usr/bin/python3

import sys
import pyvips

original = pyvips.Image.new_from_file(sys.argv[1] + "[n=-1]")
page_height = original.get_page_height()
n_pages = original.get_n_pages()

img = []
for i in range(0, n_pages):
  x = i * page_height
  cropped = original.crop(0, x, original.width, page_height / 2)
  flipped = cropped.flip('vertical')
  img.append(cropped)
  img.append(flipped)

image = pyvips.Image.arrayjoin(img, across=1)
image.set('page-height', page_height - (page_height % 2 if 1 else 0))
image.write_to_file(sys.argv[2])
```

This also seems to segfault, so it looks like this is, in fact, an issue with libvips. I've reported this as libvips/libvips#3835.

**Comment by TheEssem** [comment] 2024-01-29 19:42
Looks like there's now an open PR to fix this. On current/older versions of libvips, if you're fine with potentially using more memory, you can put `VIPS_DISC_THRESHOLD=1g` in your .env file to work around the issue.

Closing as fixed.

**Closed by TheEssem** 2024-01-29 19:42 UTC
Labels: bug
