### ISSUE TITLE
adding a both top and bottom text with already multiple inputs makes it cluncky?

### ISSUE THREAD

**Issue by Imeguras** [esmBot/esmBot#139] opened 2021-07-10 05:47 UTC
Message: Error: Request timed out (>16000ms) on POST /channels/702245737861480519/messages

Stack Trace: Error: Request timed out (>16000ms) on POST /channels/702245737861480519/messages
    at Timeout._onTimeout (/home/esmBot/esmBot/node_modules/eris-sharder/src/structures/SyncedRequestHandler.js:20:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by TheEssem** [comment] 2021-07-10 13:00
Duplicate of #138

**Closed by TheEssem** 2021-07-10 13:00 UTC
