### ISSUE TITLE
Loop ended before all servers could be checked

### ISSUE THREAD

**Issue by TypicalJam** [esmBot/esmBot#133] opened 2021-06-30 19:08 UTC
Message: Error: Loop ended before all servers could be checked

Stack Trace: Error: Loop ended before all servers could be checked
    at getIdeal (/home/esmBot/esmBot/utils/image.js:173:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/home/esmBot/esmBot/utils/image.js:178:25)

**Comment by TheEssem** [comment] 2021-11-04 15:23
Seems to no longer occur, closing.

**Comment by TheEssem** [comment] 2021-11-25 23:31
Never mind, I might take a closer look at this now that I know the cause.

**Comment by TheEssem** [comment] 2023-09-12 20:09
This seems to have long been fixed, closing.

**Closed by TheEssem** 2023-09-12 20:09 UTC
Labels: bug, server
