### ISSUE TITLE
Error: Magick: unable to create temporary file 'insert tenor image link here': No such file or directory @ error/delegate.c/InvokeDelegate/1854

### ISSUE THREAD

**Issue by Winbloo** [esmBot/esmBot#78] opened 2021-03-14 22:48 UTC
unable to make &caption on gifs
[error.txt](https://github.com/esmBot/esmBot/files/6137779/error.txt)

**Comment by gillyw33d** [comment] 2021-03-14 22:51
No image manipulation works

**Comment by TheEssem** [comment] 2021-03-14 22:54
Duplicate of #77

**Closed by TheEssem** 2021-03-14 22:54 UTC
