### ISSUE TITLE
The application did not respond.

### ISSUE THREAD

**Issue by Cephalaspis** [esmBot/esmBot#378] opened 2023-04-21 20:40 UTC
### Describe the bug

Tried to use /caption, but the bot only returns "The application did not respond". Also tried /ancient, with the same result.

### Steps to reproduce

1. Type any command, for example /ancient.

### Screenshots

![image](https://user-images.githubusercontent.com/77509951/233730392-b027ad6b-ecfa-454c-aa54-f665c2bd1f29.png)

### Self-hosted instance?

No

### Additional context

It worked fine about 2 months ago.

**Comment by TheEssem** [comment] 2023-04-21 23:20
Duplicate of #310

**Closed by TheEssem** 2023-04-21 23:20 UTC
Labels: bug
