### ISSUE TITLE
Uh oh! I ran into an error while running this command. Please report the content of the attached file here or on the esmBot Support server:

### ISSUE THREAD

**Issue by nico2113** [esmBot/esmBot#79] opened 2021-03-14 22:54 UTC
[error (1).txt](https://github.com/esmBot/esmBot/files/6137801/error.1.txt)

**Comment by TheEssem** [comment] 2021-03-14 22:56
Duplicate of #77

**Closed by TheEssem** 2021-03-14 22:56 UTC

**Comment by nico2113** [comment] 2021-03-14 23:01
thanks
