### ISSUE TITLE
It told me to report this error here

### ISSUE THREAD

**Issue by CarlosRollo** [esmBot/esmBot#255] opened 2022-04-11 14:23 UTC
### Describe the bug

Message: Magick: zero-length blob not permitted `​' @​ error/blob.c/BlobToImage/446

Stack Trace: undefined

### Self-hosted instance?

No

**Comment by samhza** [comment] 2022-04-11 14:29
What image/command did you use?

**Comment by CarlosRollo** [comment] 2022-04-12 17:16
https://cdn.discordapp.com/attachments/846298836301643776/963075225212309554/IMG_20220411_155425.jpg
&caption srasz

**Comment by TheEssem** [comment] 2022-04-27 01:51
Duplicate of #238

**Closed by TheEssem** 2022-04-27 01:51 UTC
Labels: bug
