### ISSUE TITLE
"/lengthen" doesn't work

### ISSUE THREAD

**Issue by ChrisGitu02** [esmBot/esmBot#415] opened 2023-10-26 18:05 UTC
### Command that caused the error

/lengthen [url: https://nrk.no/]

### Steps to reproduce

1. write command /lengthen [url: https://nrk.no/]

### Self-hosted instance?

No

### Error file

Message: InvalidArgumentError: Invalid URL protocol: the URL must start with `​http:`​ or `​https:`​.
    at Object.parseURL (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.23.0/node_modules/undici/lib/core/util.js:51:13)
    at /home/esmBot/esmBot/node_modules/.pnpm/undici@​5.23.0/node_modules/undici/index.js:78:18
    at LengthenCommand.run (file:///home/esmBot/esmBot/commands/general/lengthen.js?v=25:12:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by TheEssem** [comment] 2023-10-27 04:21
It seems to work here on both the main bot and latest commit with the URL you gave, are you able to reproduce this with another URL?

**Comment by TheEssem** [comment] 2024-08-08 01:35
Seeing as the issue author hasn't responded and I can't reproduce this, I'm closing this issue for now. If anyone else is able to reproduce this, please comment and I'll reopen it.

**Closed by TheEssem** 2024-08-08 01:35 UTC
Labels: bug
