### ISSUE TITLE
Error trying to caption images / gifs &Caption &Caption2 etc.

### ISSUE THREAD

**Issue by LambyTheLamb** [esmBot/esmBot#40] opened 2020-12-31 18:06 UTC
Had this problem for the last day or so, seems like it's fairly frequent for others too every other command seems to work if it isn't an image editing command.
Error .txt as follows; 
Message: Error: EMFILE: too many open files, open '/home/esmBot/esmBot/api/index.js'

Stack Trace: undefined

**Comment by TheEssem** [comment] 2020-12-31 18:57
Duplicate of #37, follow that issue if you want to get updates on it

**Closed by TheEssem** 2020-12-31 18:57 UTC
