### ISSUE TITLE
bot aint working no more

### ISSUE THREAD

**Issue by smartestidiot1** [esmBot/esmBot#395] opened 2023-06-24 12:26 UTC
### Command that caused the error

i tried using /speechbubble and other cmds like /gif

### Image that caused the error

https://cdn.discordapp.com/attachments/1121473276556869652/1121475864039800872/4-n.png

### Steps to reproduce

1. i said /gif
2. i put image: https://cdn.discordapp.com/attachments/1121473276556869652/1121475864039800872/4-n.png
3. then it dont work 

### Self-hosted instance?

Yes

### Error file

Message: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:182:24)
    at /home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:129:46
    at Immediate._onImmediate (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:170:9)
    at processImmediate (node:internal/timers:466:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}

Stack Trace: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:182:24)
    at /home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:129:46
    at Immediate._onImmediate (/home/esmBot/esmBot/node_modules/.pnpm/undici@​5.22.1/node_modules/undici/lib/core/connect.js:170:9)
    at processImmediate (node:internal/timers:466:21)

### Additional context

nil

**Comment by TheEssem** [comment] 2023-06-24 14:03
Duplicate of #393

**Closed by TheEssem** 2023-06-24 14:03 UTC
Labels: bug
