### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by LowIntelligenceSpecimen** [esmBot/esmBot#353] opened 2023-02-04 13:16 UTC
### Command that caused the error

/caption text:dead chat xd

### Image that caused the error

https://cdn.discordapp.com/attachments/1030579554722533409/1071415892170248303/IMG_1892.gif

### Steps to reproduce

1. Type the link to the image in chat
2. Select it as the image to be used for the next command
3. Type /caption text:dead chat xd in chat

### Self-hosted instance?

No

### Error file

Message: BodyTimeoutError: Body Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/client.js:906:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_BODY_TIMEOUT'
}

Stack Trace: BodyTimeoutError: Body Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/client.js:906:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7)

**Comment by TheEssem** [comment] 2023-09-12 19:54
Duplicate of #348

**Closed by TheEssem** 2023-09-12 19:54 UTC
Labels: bug
