### ISSUE TITLE
Incredibox motivate

### ISSUE THREAD

**Issue by UsernameNoIdeas** [esmBot/esmBot#263] opened 2022-05-05 22:54 UTC
### Command that caused the error

&motivate Incredibox

### Steps to reproduce

Type &motivate Incredibox
Wait

### Self-hosted instance?

No

### Error file

```
Message: Magick: zero-length blob not permitted `​' @​ error/blob.c/BlobToImage/446

Stack Trace: undefined
```

**Comment by TheEssem** [comment] 2022-05-20 03:05
Duplicate of #238

**Closed by TheEssem** 2022-05-20 03:05 UTC
Labels: bug
