### ISSUE TITLE
Error regarding Select Image Command

### ISSUE THREAD

**Issue by mcJofsel** [esmBot/esmBot#342] opened 2022-12-24 17:31 UTC
### Command that caused the error

Select Image

### Image that caused the error

https://cdn.discordapp.com/attachments/919679563481620533/1056262331379757108/image.png

### Steps to reproduce

1. Go to Apps.
2. Click on Select Image
3. See error

### Self-hosted instance?

Yes

### Error file

```
Message: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.createMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:151:46)
```

**Comment by TheEssem** [comment] 2022-12-24 19:17
Duplicate of #339

**Closed by TheEssem** 2022-12-24 19:17 UTC
Labels: bug
