### ISSUE TITLE
Message: Error: Timed out when requesting

### ISSUE THREAD

**Issue by SmonkyWontBeatYa** [esmBot/esmBot#404] opened 2023-07-26 15:42 UTC
### Command that caused the error

Apps > Select Image

### Image that caused the error

https://media.discordapp.net/attachments/1114800785113501777/1133785325412560896/ezgif-3-fa83e51894.gif?width=599&height=1365

### Steps to reproduce

Right click on gif
Apps
Select Image

### Self-hosted instance?

Yes

### Error file

Message: Error: Timed out when requesting https://media.discordapp.net/attachments/1114800785113501777/1133785325412560896/ezgif-3-fa83e51894.gif
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async checkImages (file:///home/esmBot/esmBot/utils/imagedetect.js:135:14)

**Comment by TheEssem** [comment] 2023-09-05 04:06
Duplicate of #399

**Closed by TheEssem** 2023-09-05 04:06 UTC
Labels: bug
