### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by LSinister** [esmBot/esmBot#179] opened 2021-11-15 00:22 UTC
### Command that caused the error

@esmBot bandicam

### Image that caused the error

i don't know :/

### Self-hosted instance?

No

### Error file

```

```
[error.txt](https://github.com/esmBot/esmBot/files/7535021/error.txt)

**Comment by TheEssem** [comment] 2021-11-15 00:26
Duplicate of #178

**Closed by TheEssem** 2021-11-15 00:26 UTC
Labels: bug, server
