### ISSUE TITLE
Stream destroyed

### ISSUE THREAD

**Issue by TheGregster1111** [esmBot/esmBot#71] opened 2021-03-01 09:10 UTC
Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:329:5)
    at Socket.Writable.write (node:internal/streams/writable:331:11)
    at /home/esmBot/esmBot/utils/image.js:113:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by TheEssem** [comment] 2021-03-03 02:45
Duplicate of #70

**Closed by TheEssem** 2021-03-03 02:45 UTC
