### ISSUE TITLE
ESMBOT ISSUES

### ISSUE THREAD

**Issue by ScreamQueenzPod** [esmBot/esmBot#443] opened 2024-03-31 01:10 UTC
### Command that caused the error

/meme

### Image that caused the error

https://discord.com/channels/929220139080097842/929233100708393031/1223769798488363059

### Steps to reproduce

[error.txt](https://github.com/esmBot/esmBot/files/14813740/error.txt)

### Self-hosted instance?

Yes

### Error file

```Message: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Channels.js:447:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:149:100)
    at MemeCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20) {
  code: 50001
}

Stack Trace: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Channels.js:447:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:149:100)
    at MemeCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

```

**Comment by TheEssem** [comment] 2024-03-31 01:18
Duplicate of #419

**Closed by TheEssem** 2024-03-31 01:18 UTC
Labels: bug
