### ISSUE TITLE
bot breaks while runing gif commands

### ISSUE THREAD

**Issue by Sebseb2222** [esmBot/esmBot#96] opened 2021-04-23 16:25 UTC
Message: Error: Magick: delegate failed `'curl' -s -k -L -o '%u.dat' 'https:%M'' @ error/delegate.c/InvokeDelegate/1898

Stack Trace: Error: Magick: delegate failed `'curl' -s -k -L -o '%u.dat' 'https:%M'' @ error/delegate.c/InvokeDelegate/1898
    at Socket.<anonymous> (/home/esmBot/esmBot/utils/image.js:88:36)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Collapse
error.txt
1 KB

**Comment by TheEssem** [comment] 2021-04-23 16:30
Duplicate of #95

**Closed by TheEssem** 2021-04-23 16:30 UTC
