### ISSUE TITLE
caption command not morking

### ISSUE THREAD

**Issue by guy0on0the0internet** [esmBot/esmBot#185] opened 2021-11-25 21:01 UTC
### Command that caused the error

&caption white women when they hear on the radio the crapiest music you've ever heard in your life

### Image that caused the error

https://tenor.com/view/sesame-street-sped-up-dj-elmo-dancing-ernie-dance-gif-23245789

### Self-hosted instance?

No

### Error file

Message: Loop ended before all servers could be checked

Stack Trace: undefined

**Comment by HotelTransylvania** [comment] 2021-11-25 23:01
I also keep getting the problem.

**Comment by TheEssem** [comment] 2021-11-25 23:32
Duplicate of #133

**Closed by TheEssem** 2021-11-25 23:32 UTC
Labels: bug
