### ISSUE TITLE
&caption on certain images do not work

### ISSUE THREAD

**Issue by Hna1243** [esmBot/esmBot#187] opened 2021-11-26 01:38 UTC
### Command that caused the error

&caption 192.364.93.697

### Image that caused the error

https://media.discordapp.net/attachments/905624678494797867/913603439223791666/Tomato-ketchup-illustration.png

### Steps to reproduce

1. Go to '&img heinz tomato ketchup'
2. download the first image (https://media.discordapp.net/attachments/905624678494797867/913603439223791666/Tomato-ketchup-illustration.png)
3. Do a &caption command

### Self-hosted instance?

No

### Error file

```
Message: WebAssembly.instantiate(): Out of memory: wasm memory

Stack Trace: undefined
```

### Additional context

the ip is completely made up. it is not a real ip address.

**Comment by TheEssem** [comment] 2021-11-26 03:09
Duplicate of #157

**Closed by TheEssem** 2021-11-26 03:09 UTC
Labels: bug
