### ISSUE TITLE
Message: WebAssembly.instantiate(): Out of memory: wasm memory  Stack Trace: undefined

### ISSUE THREAD

**Issue by bneils** [esmBot/esmBot#188] opened 2021-11-26 02:09 UTC
### Command that caused the error

&caption "ooooo 😎"

### Image that caused the error

https://cdn.discordapp.com/attachments/907040657401585707/907041470454825010/image0-93.jpg

### Steps to reproduce

1. Go to image
2. Reply to image with command at Nov 25 9:06PM EST

### Self-hosted instance?

No

### Error file

```
Message: WebAssembly.instantiate(): Out of memory: wasm memory

Stack Trace: undefined
```

### Additional context

Nothing else. Was quite simple.

**Comment by not-pyroman** [comment] 2021-11-26 02:33
I get this too
[error.txt](https://github.com/esmBot/esmBot/files/7605927/error.txt)

**Comment by TheEssem** [comment] 2021-11-26 03:09
Duplicate of #157

**Closed by TheEssem** 2021-11-26 03:09 UTC
Labels: bug
