### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZenBooda1** [esmBot/esmBot#124] opened 2021-05-17 19:56 UTC
ඞcaption
Post the exact command that caused the error.

https://tenor.com/view/justin-bieber-bieber-gif-19877431
If the error is regarding an image command, please post a direct link to the image here.

**To Reproduce**
1. Go to Discord text Channel
2. Post link (https://tenor.com/view/justin-bieber-bieber-gif-19877431)
3. type ඞcaption (I use ඞ for default to start command)

No
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?

[error.txt](https://github.com/esmBot/esmBot/files/6496526/error.txt)

Post the contents of the error file here.
Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:363:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/esmBot/esmBot/utils/image.js:154:21
    at new Promise (<anonymous>)
    at /home/esmBot/esmBot/utils/image.js:153:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

When I did ඞspeed. It also didn't work

**Comment by TheEssem** [comment] 2021-05-17 20:05
Duplicate of #70

**Closed by TheEssem** 2021-05-17 20:05 UTC
