### ISSUE TITLE
/caption bug

### ISSUE THREAD

**Issue by alec-jensen** [esmBot/esmBot#366] opened 2023-03-30 13:31 UTC
### Describe the bug

Idk I did /caption for this image: https://tenor.com/view/sprawsm-pickle-so-good-theskeletonappears-gif-24688164 with this text: "man this pickle is so good!"

https://cdn.discordapp.com/attachments/974120057770750006/1090991199436951583/error.txt

### Steps to reproduce

No idea

### Expected behavior

No error

### Self-hosted instance?

No

**Comment by TheEssem** [comment] 2023-03-30 20:38
Duplicate of #338

**Closed by TheEssem** 2023-03-30 20:38 UTC
Labels: bug
