### ISSUE TITLE
Error code upon using caption command

### ISSUE THREAD

**Issue by burnetize** [esmBot/esmBot#76] opened 2021-03-10 23:06 UTC
Was making a meme with the bot (as per usual) and it gave me a message saying to send this file to the github, so here it is:
[error.txt](https://github.com/esmBot/esmBot/files/6119347/error.txt)

**Comment by TheEssem** [comment] 2021-03-10 23:36
Duplicate of #75

**Closed by TheEssem** 2021-03-10 23:36 UTC
