### ISSUE TITLE
PNG/JPEG/etc to GIF command

### ISSUE THREAD

**Issue by veast-network** [esmBot/esmBot#277] opened 2022-06-19 00:11 UTC
### Describe the request

Title. Basically a image to GIF command so you can easily favorite the GIF. For example having a speechbubble image and being able to favorite it so you can send it quickly.

**Comment by djtravz** [comment] 2022-06-20 01:37
this is an awesome idea

**Comment by dd-pardal** [comment] 2022-06-20 13:08
GIF is a horrible format. If you convert an image to GIF, you loose a lot of quality. It's not as convenient, but I suggest you save the images in a folder so you can upload them easily when you want to.

**Comment by veast-network** [comment] 2022-06-20 18:40
it isn't that bad, and I don't think you would need extremely high quality
on a image that has a speechbubble on it

**Comment by djtravz** [comment] 2022-06-21 00:50
It only really needs to be like 500px for what I'm picturing
Almost like a free way to send stickers

**Comment by bjcscat** [comment] 2022-06-21 04:06
I might do this

**Comment by TheEssem** [comment] 2022-06-22 23:55
Duplicate of #242, feel free to continue discussion there.

**Closed by TheEssem** 2022-06-22 23:55 UTC
Labels: enhancement
