### ISSUE TITLE
Error: Stream Destroyed

### ISSUE THREAD

**Issue by TheMattMoney** [esmBot/esmBot#117] opened 2021-05-09 23:46 UTC
**Command that caused the error**
&speed

**Image that caused the error**
https://media.tenor.co/videos/78b1555a3c3769d21ea7343b494afc72/mp4

**To Reproduce**
1. Post the image link above
2. Enter the command "&speed"

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?

No

**Error file**
```
Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:363:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/esmBot/esmBot/utils/image.js:155:21
    at new Promise (<anonymous>)
    at /home/esmBot/esmBot/utils/image.js:154:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Additional context**
Done in a completely empty server with just me and the bot

**Comment by TheEssem** [comment] 2021-05-25 14:35
Duplicate of #70

**Closed as completed by TheEssem** 2021-05-25 14:35 UTC
