### ISSUE TITLE
esmBot gives error when trying to make captioned gif

### ISSUE THREAD

**Issue by realdep** [esmBot/esmBot#106] opened 2021-05-04 07:04 UTC
![Capture](https://user-images.githubusercontent.com/9782679/116970078-fbe8c880-acbf-11eb-8af0-a2206260f4ca.PNG)

```text
Message: Error: Magick: no decode delegate for this image format `DAT' @ error/constitute.c/ReadImage/572

Stack Trace: Error: Magick: no decode delegate for this image format `DAT' @ error/constitute.c/ReadImage/572
    at Socket.<anonymous> (/home/esmBot/esmBot/utils/image.js:88:36)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by TheEssem** [comment] 2021-05-05 02:34
What image/command did you run to get this?

**Comment by realdep** [comment] 2021-05-05 06:34
> What image/command did you run to get this?
[this](https://media.giphy.com/media/Ckaw2djPlXYFQMlTYr/giphy.gif)

i just tried with another image and it works so probably a problem with the gif/link itself

**Comment by TheEssem** [comment] 2021-05-05 16:35
Giphy images seem to cause quite a few issues, likely due to most of the URLs redirecting to their web pages. Closing this as a duplicate of #72, you can follow that issue for updates.

**Closed by TheEssem** 2021-05-05 16:35 UTC
