### ISSUE TITLE
"I ran into an error while running this command.

### ISSUE THREAD

**Issue by maticerocks** [esmBot/esmBot#398] opened 2023-07-04 04:57 UTC
### Command that caused the error

gif image: [attachment] togif: true"

### Image that caused the error

https://cdn.discordapp.com/attachments/1115886477696569434/1125650118318759977/image_20_-removebg-preview.png

### Steps to reproduce

Message: DiscordRESTError: Interaction has already been acknowledged.
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:176:46)
    at GIFCommand.acknowledge (file:///home/esmBot/esmBot/classes/command.js:59:30)
    at GIFCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:34:49)
    at default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 40060
}

Stack Trace: DiscordRESTError: Interaction has already been acknowledged.
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.0/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:176:46)
    at GIFCommand.acknowledge (file:///home/esmBot/esmBot/classes/command.js:59:30)
    at GIFCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:34:49)
    at default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Self-hosted instance?

Yes

### Error file

```
https://github.com/esmBot/esmBot/files/11944552/error.txt

```

**Comment by TheEssem** [comment] 2023-07-04 21:01
Duplicate of #336

**Closed by TheEssem** 2023-07-04 21:01 UTC
Labels: bug
