### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by kangbani8** [esmBot/esmBot#310] opened 2022-09-06 18:09 UTC
### Command that caused the error

all the commands that i typed out, (i.e /speechbubble, etc etc)

### Image that caused the error

https://media.discordapp.net/attachments/976790361022283786/1016771573648199710/unknown.png

### Steps to reproduce

it has been personally bugging me for the last few days or so, don't know if i was supposedly blacklisted (if that exists, please remove me from that fucking list thanks)

### Self-hosted instance?

No

### Error file

`

### Additional context

well, as i said any command i tried using is immediately gone and replaced with the error, it is possible that the 3 second timeout for commands IS screwing with the bot, not sure.

**Comment by kangbani8** [comment] 2022-09-06 18:10
if you want more information contact me @doorman#1118 on Discord.

**Comment by kangbani8** [comment] 2022-09-06 18:11
tried modifying it with the Options panel, still gave me the same exact error as mentioned above in the post.

**Comment by TheEssem** [comment] 2022-09-11 04:51
Possible duplicate of #301? It's a different message though which makes it hard to tell

**Comment by TheEssem** [comment] 2023-06-15 21:16
Now tracking in #383, please follow that issue.

**Closed** 2023-06-15 21:16 UTC
Labels: bug
