### ISSUE TITLE
commands are not working for gifs

### ISSUE THREAD

**Issue by Feneno** [esmBot/esmBot#75] opened 2021-03-10 22:28 UTC
0 commands are working just giving this text after

https://cdn.discordapp.com/attachments/683491690832855125/819334800372138004/error.txt 

![image](https://user-images.githubusercontent.com/80429822/110706522-ff7f3800-81c5-11eb-976e-976ed101a2a4.png)

**Comment by TheEssem** [comment] 2021-03-10 23:37
Duplicate of #74

**Closed by TheEssem** 2021-03-10 23:37 UTC
