### ISSUE TITLE
Caption and Caption2 doesn't work

### ISSUE THREAD

**Issue by Koolfudsim** [esmBot/esmBot#123] opened 2021-05-17 19:18 UTC
Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:363:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)

**Comment by TheEssem** [comment] 2021-05-17 20:05
Duplicate of #70

**Closed by TheEssem** 2021-05-17 20:05 UTC
