### ISSUE TITLE
Timed out when requesting [image url]

### ISSUE THREAD

**Issue by thepwrtank18** [esmBot/esmBot#407] opened 2023-08-03 18:23 UTC
### Command that caused the error

/caption text: if you think abt it wiiu rly isnt doin that bad i mean if they have around 6 mil units sell thers only like 7 millon ppl on earth so almost every1 has a wiiu image: [attachment]

### Image that caused the error

https://onedrive.live.com/download?resid=14FA5317997FD8E5%2170988&authkey=%21AFlhSgaW-hndayU&width=640&height=640

### Steps to reproduce

1. Download gif to use
2. Run command above
3. See error

### Self-hosted instance?

No

### Error file

```
Message: Error: Timed out when requesting https://media.discordapp.net/ephemeral-attachments/991195178360635431/1136725437775614123/the-rock-explaining.gif
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:150:24)
    at async CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:36)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

Stack Trace: Error: Timed out when requesting https://media.discordapp.net/ephemeral-attachments/991195178360635431/1136725437775614123/the-rock-explaining.gif
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:150:24)
    at async CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:36)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)
```

**Comment by thepwrtank18** [comment] 2023-08-03 18:31
I tried compressing the file to less than 8 MB (discord's previous file limit), and it still doesn't work.

**Comment by TheEssem** [comment] 2023-09-05 04:06
Duplicate of #399

**Closed by TheEssem** 2023-09-05 04:06 UTC
Labels: bug
