### ISSUE TITLE
your bot fucking sucks

### ISSUE THREAD

**Issue by bruhmomentarily** [esmBot/esmBot#365] opened 2023-03-29 23:08 UTC
### Command that caused the error

/caption text: 👍 link: https://tenor.com/view/cat-thumbs-up-middle-finger-cat-gif-23407917

### Image that caused the error

https://tenor.com/view/cat-thumbs-up-middle-finger-cat-gif-23407917

### Steps to reproduce

ok

### Self-hosted instance?

Yes

### Error file

```
Message: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:177:46)
    at CaptionCommand.acknowledge (file:///root/esmBot/classes/command.js:54:30)
    at CaptionCommand.run (file:///root/esmBot/classes/imageCommand.js:32:49)
    at default (file:///root/esmBot/events/interactionCreate.js:28:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 10062
}

Stack Trace: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.5.2-dev.77e7b1d_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:177:46)
    at CaptionCommand.acknowledge (file:///root/esmBot/classes/command.js:54:30)
    at CaptionCommand.run (file:///root/esmBot/classes/imageCommand.js:32:49)
    at default (file:///root/esmBot/events/interactionCreate.js:28:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional context

[https://tenor.com/view/esmbot-gif-22032974](url)

**Comment by TheEssem** [comment] 2023-03-30 00:03
Duplicate of #338/#339

**Closed by TheEssem** 2023-03-30 00:03 UTC
Labels: bug
