### ISSUE TITLE
Error keeps popping up when i use &caption and &caption2

### ISSUE THREAD

**Issue by GavinTLD** [esmBot/esmBot#38] opened 2020-12-30 13:34 UTC
[error.txt](https://github.com/esmBot/esmBot/files/5754340/error.txt)

idk why it keeps doing this but im just using this bot for creating memes thats all, please fix asap

**Comment by TheEssem** [comment] 2020-12-30 15:53
dupe of #37

**Closed by TheEssem** 2020-12-30 15:53 UTC
