### ISSUE TITLE
Dunno esmBot told me to report this idk what's happening tbh

### ISSUE THREAD

**Issue by ATSRO** [esmBot/esmBot#193] opened 2021-11-28 21:27 UTC
### Describe the bug

[error.txt](https://github.com/esmBot/esmBot/files/7614404/error.txt)

### Self-hosted instance?

Yes

### Additional context

Bot stopped working and keeps sending error on every command

**Comment by ATSRO** [comment] 2021-11-28 21:28
Ignore the steps to reproduce just use any cpmmand it will happen

**Comment by TheEssem** [comment] 2021-11-28 21:29
Duplicate of #192

**Closed by TheEssem** 2021-11-28 21:29 UTC
Labels: bug
