### ISSUE TITLE
I have ran into error

### ISSUE THREAD

**Issue by Zeninntoji** [esmBot/esmBot#471] opened 2024-09-04 08:42 UTC
### Command that caused the error

/music play query:those eyes

### Self-hosted instance?

Yes

### Error file

```

```
Message: Error: The voice connection is not established in 15 seconds
    at Connection.connect (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.0.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:335:15)
    at async Shoukaku.joinVoiceChannel (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.0.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:1315:7)
    at async play (file:///home/esmBot/esmBot/utils/soundplayer.js:130:32)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=99:20:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:52:20)

Stack Trace: Error: The voice connection is not established in 15 seconds
    at Connection.connect (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.0.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:335:15)
    at async Shoukaku.joinVoiceChannel (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​4.0.1_bufferutil@​4.0.8/node_modules/shoukaku/dist/index.mjs:1315:7)
    at async play (file:///home/esmBot/esmBot/utils/soundplayer.js:130:32)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=99:20:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:52:20)

**Comment by TheEssem** [comment] 2024-09-04 14:07
Duplicate of #314

**Closed by TheEssem** 2024-09-04 14:07 UTC
Labels: bug
