### ISSUE TITLE
Error when doing &caption and image editing commands like &blur or &bandicam

### ISSUE THREAD

**Issue by Maxter30** [esmBot/esmBot#109] opened 2021-05-05 14:42 UTC
When I try to do these commands on the bot I get this message and don't know what it is. Any help is appreciated.

Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:363:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/esmBot/esmBot/utils/image.js:149:21
    at new Promise (<anonymous>)
    at /home/esmBot/esmBot/utils/image.js:148:12

**Comment by TheEssem** [comment] 2021-05-05 16:32
Duplicate of #70

**Closed by TheEssem** 2021-05-05 16:32 UTC
