### ISSUE TITLE
Bot randomly uses all available CPU

### ISSUE THREAD

**Issue by dkay0670** [esmBot/esmBot#357] opened 2023-02-25 00:37 UTC
### Describe the bug

The bot will randomly use 100% cpu until restarted.

### Steps to reproduce

Unknown, the only commands that were run are avatar, globe, and bounce. The bot runs the commands fine and doesn't result in high CPU, only hours later.

### Expected behavior

Bot doesn't use all the CPU at random

### Screenshots

![image](https://user-images.githubusercontent.com/63021402/221325621-850b0e01-6bf3-42e0-a6e9-1a733e4374ea.png)

### Self-hosted instance?

Yes

### Additional context

Running in a docker container.

**Comment by dx9er** [comment] 2023-02-27 14:20
I have the same issue on PM2 using Ubuntu, no Docker. It causes playback in voice chats to be sluggish, stuttering and cutting in and out. It's most likely a byproduct of the CPU absolutely chugging.

![ArpdLG1yPw](https://user-images.githubusercontent.com/30122437/221587188-b9477937-8de7-4d1d-ae2f-6b6b7ce45a06.png)

I haven't added restart automation, I only restart manually if I update or encounter an issue live. So far, this has never been an issue until the latest commit even with hundreds of hours of uptime.

I'm reverting to [5ba033683727ea1cedc7ec5b4c1268646942c24b](https://github.com/esmBot/esmBot/commit/3c16599126aef3c70907f22b2a722bfbe99a522a) to see if this issue persists.

**Comment by dkay0670** [comment] 2023-02-27 22:42
Interesting, I noticed someone in the discord support server having the same issue quite a while ago but maybe this is something different.
![image](https://user-images.githubusercontent.com/63021402/221702591-a51dbf2a-40a8-4336-8ebe-83147fde390d.png)

**Comment by dkay0670** [comment] 2023-03-03 01:02
hey @dx9er! any updates on this? did reverting to that commit fix it for you?

**Comment by dx9er** [comment] 2023-03-03 15:42
Hey @dkay0670, sorry for the holdup. I thought I'd need some time to produce results (because on the previous screenshot I had the bot on for so long), but seems like the bot has already made up its mind.
Did it fix? Yes and no. Yes, as in all the cores are no longer being hogged. No, as in it is now only using up a single core.

![single_core_usage](https://user-images.githubusercontent.com/30122437/222761471-0654e7dc-2cc3-4c5b-8087-f5324519e0c0.png)

It seems to switch around the core that it's using. This is a shot in the dark, but something along this commit timeline may have made esmBot spawn more sub-processes(?) when core usage started to be overwhelming.
Although an important note is that I unfortunately forgot to rebuild the natives as I reverted back. I'm going to stay on the same commit simply to exhaust all the possible points of failure. It should produce results in about 2 days at most and I'll try and get back to you then.

**Comment by dkay0670** [comment] 2023-03-03 16:44
Very interesting... I'll do some diffs and see if anything like that changed since that commit, but that does seem to make some sense

**Comment by TheEssem** [comment] 2023-03-04 05:00
I actually saw something similar on devbot when testing, except it was happening on the WS image server process instead of the bot process. I'm guessing it's most likely related to the natives refactor.

**Comment by dx9er** [comment] 2023-03-05 19:15
Day 2, nothing so far. Usage is next to none in idle. If nothing comes up I can say with certainty this issue is because of some commit on natives since [5ba033683727ea1cedc7ec5b4c1268646942c24b](https://github.com/esmBot/esmBot/commit/3c16599126aef3c70907f22b2a722bfbe99a522a).

**Comment by dx9er** [comment] 2023-03-07 01:19
End of day 3, the bug is back. One core is entirely used up like before. Genuinely stumped on what the problem could be.

**Comment by lzgirlcat** [comment] 2023-03-07 19:14
I'm experiencing the same problem, after 1-2 days of operation node starts using up all of the cpu

**Comment by TheEssem** [comment] 2023-03-08 20:51
This seems to be a duplicate of #354, discussion should continue there.

**Closed by TheEssem** 2023-03-08 20:51 UTC
Labels: bug

**Comment by dkay0670** [comment] 2023-03-09 03:10
> This seems to be a duplicate of #354, discussion should continue there.

Are there plans to fix this? That issue is a month old and has no replies.

**Comment by TheEssem** [comment] 2023-03-09 15:54
> > This seems to be a duplicate of #354, discussion should continue there.
> 
> Are there plans to fix this? That issue is a month old and has no replies.

This is definitely a bad issue and we need to find a fix for it, I'm just doing what I usually do with other duplicate issues
