### ISSUE TITLE
Certain character combinations break ImageMagick commands that accept text input

### ISSUE THREAD

**Issue by Jacherr** [esmBot/esmBot#237] opened 2022-02-20 14:23 UTC
### Describe the bug

Certain character combinations, such as `<t` (in the context of a command like `&caption <t`), will cause the Pango parser to break and esmBot returns an error.

### Steps to reproduce

Run any ImageMagick-powered command with a text argument, and use `<t` (or similar) as the argument

### Expected behavior

The text provided is displayed as a caption on the image

### Screenshots

![image](https://user-images.githubusercontent.com/40544507/154847384-cc2fd61d-47f7-4a47-afe3-a9d7dc719979.png)

### Self-hosted instance?

No

**Comment by TheEssem** [comment] 2022-02-20 14:35
Interesting - the bot [should be filtering those characters accordingly](https://github.com/esmBot/esmBot/blob/4ef2ce75262b1ca628313614a3a4c2bdbf13aa3f/commands/image-editing/meme.js#L9). I looked into this and after running the same command as in the screenshot on both the main bot and my dev instance, and they both seemed to work as intended.

**Comment by TheEssem** [comment] 2022-06-16 02:14
Can't reproduce, closing.

**Closed by TheEssem** 2022-06-16 02:14 UTC
Labels: bug
