### ISSUE TITLE
Music doesn't work

### ISSUE THREAD

**Issue by Coconutpandas** [esmBot/esmBot#476] opened 2024-09-19 22:55 UTC
### Command that caused the error

/music play

### Self-hosted instance?

Yes

### Error file

Message: RestError: Session not found
    at Rest.fetch (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@â€‹4.1.1_bufferutil@â€‹4.0.8/node_modules/shoukaku/dist/index.mjs:949:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.sendServerUpdate (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@â€‹4.1.1_bufferutil@â€‹4.0.8/node_modules/shoukaku/dist/index.mjs:709:5)
    at async Shoukaku.joinVoiceChannel (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@â€‹4.1.1_bufferutil@â€‹4.0.8/node_modules/shoukaku/dist/index.mjs:1332:7)
    at async play (file:///home/esmBot/esmBot/utils/soundplayer.js:129:32)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=101:20:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:57:20) {
  timestamp: 1726785707153,
  status: 404,
  error: 'Not Found',
  trace: undefined,
  path: '/v4/sessions/7fdonrxiqqpwonic/players/1100106220909637746'
}

Stack Trace: RestError: Session not found
    at Rest.fetch (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@â€‹4.1.1_bufferutil@â€‹4.0.8/node_modules/shoukaku/dist/index.mjs:949:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.sendServerUpdate (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@â€‹4.1.1_bufferutil@â€‹4.0.8/node_modules/shoukaku/dist/index.mjs:709:5)
    at async Shoukaku.joinVoiceChannel (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@â€‹4.1.1_bufferutil@â€‹4.0.8/node_modules/shoukaku/dist/index.mjs:1332:7)
    at async play (file:///home/esmBot/esmBot/utils/soundplayer.js:129:32)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=101:20:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:57:20)

**Comment by TheEssem** [comment] 2024-09-19 22:59
Duplicate of #459

**Closed by TheEssem** 2024-09-19 22:59 UTC
Labels: bug
