### ISSUE TITLE
Caption issue

### ISSUE THREAD

**Issue by emimem-real** [esmBot/esmBot#429] opened 2024-01-12 03:55 UTC
### Command that caused the error

/caption

### Image that caused the error

https://imgur.com/68Lmpku

### Steps to reproduce

1. Go to 'gif that i wanna use'
2. Click on 'select image'
3. use /caption to put 'pov: you shouldnt have pissed off bavarian arty'

### Self-hosted instance?

No

### Error file

``` 
Message: Error: VipsForeignLoad: buffer is not in a known format
VipsForeignLoad: buffer is not in a known format
VipsForeignLoad: buffer is not in a known format

    at ImageConnection.onMessage (file:///home/esmBot/esmBot/utils/imageConnection.js:66:22)
    at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:89:45)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.dataMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:526:14)
    at Receiver.getData (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:459:17)
    at Receiver.startLoop (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:158:22)
    at Receiver._write (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)

Stack Trace: Error: VipsForeignLoad: buffer is not in a known format
VipsForeignLoad: buffer is not in a known format
VipsForeignLoad: buffer is not in a known format

    at ImageConnection.onMessage (file:///home/esmBot/esmBot/utils/imageConnection.js:66:22)
    at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:89:45)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.dataMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:526:14)
    at Receiver.getData (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:459:17)
    at Receiver.startLoop (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:158:22)
    at Receiver._write (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
```

### Additional context

it works with any other gif i try to caption

**Comment by TheEssem** [comment] 2024-01-12 04:31
Duplicate of #408

**Closed by TheEssem** 2024-01-12 04:31 UTC
Labels: bug
