### ISSUE TITLE
&caption command not working

### ISSUE THREAD

**Issue by HasanDaTop** [esmBot/esmBot#229] opened 2022-01-31 16:01 UTC
&caption command not working in „Scott The Woz“. Here‘s the file the bot sent if you need it Message: Magick: unable to read pixel cache '/tmp/magick-4LPjuX9h5iLh1TjIwR7Fr2xo7G8iXxfm': File exists @​ error/cache.c/ReadPixelCachePixels/4705

Stack Trace: undefined

**Comment by TheEssem** [comment] 2022-02-01 19:26
Duplicate of #221

**Closed by TheEssem** 2022-02-01 19:26 UTC
