### ISSUE TITLE
le fail

### ISSUE THREAD

**Issue by trrrrrrrrrrrrr** [esmBot/esmBot#376] opened 2023-04-18 22:41 UTC
### Command that caused the error

Select Image

### Image that caused the error

https://tenor.com/view/shore-coast-never-ending-loop-infinite-gif-12230198

### Steps to reproduce

Right Click -> Select Image
![image](https://user-images.githubusercontent.com/24661212/232920558-97ace215-b3cf-4eaa-b5a5-30e20271f112.png)

### Self-hosted instance?

No

### Error file

```
Message: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:177:46)
    at SelectImageCommand.acknowledge (file:///home/esmBot/esmBot/classes/command.js:58:30)
    at SelectImageCommand.run (file:///home/esmBot/esmBot/commands/message/select-image.js?v=97:7:16)
    at default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 10062
}

Stack Trace: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.6.0/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:177:46)
    at SelectImageCommand.acknowledge (file:///home/esmBot/esmBot/classes/command.js:58:30)
    at SelectImageCommand.run (file:///home/esmBot/esmBot/commands/message/select-image.js?v=97:7:16)
    at default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by TheEssem** [comment] 2023-04-19 01:26
Duplicate of #338

**Closed by TheEssem** 2023-04-19 01:26 UTC
Labels: bug
